server:
  host: "0.0.0.0"
  port: 8080
  mode: "release"

database:
  driver: "postgres"
  postgres:
    host: "${DATABASE_HOST}"
    port: 5432
    user: "${DATABASE_USER}"
    password: "${DATABASE_PASSWORD}"
    database: "${DATABASE_NAME}"
    sslmode: "require"

logger:
  level: "info"
  format: "json"
  provider: "stdout"

telemetry:
  enabled: false
  tracing_enabled: false
  metrics_enabled: false

application:
  name: "whats-provider"
  version: "1.0.0"
  environment: "production"

whatsapp:
  providers:
    zapi:
      base_url: "${ZAPI_BASE_URL}"
      client_token: "${ZAPI_CLIENT_TOKEN}"
